name: Cypress

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: cypress
        run: npm install 

      - name: Setup French Locale
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-fr
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8

      - name: Verify Locale
        run: locale

      - name: Run e2e:workshop
        working-directory: cypress
        run: npx cypress run --spec "cypress/cypress/e2e/test-trello_faire_un_filtre.cy.js"
        env:
          LANG: fr_FR.UTF-8
          LC_ALL: fr_FR.UTF-8

      - name: publish report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ./cypress/reports/html
          name: html-report
