name: Cypress

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4


      - name: Setup French Locale
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-fr
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8

      - name: Verify Locale
        run: locale

      - name: execute cypress tests
        uses: cypress-io/github-action@v6
        env:
          LANG: fr_FR.UTF-8
          LC_ALL: fr_FR.UTF-8

      - name: publish report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ./cypress/reports/html
          name: html-report
