name: Run Postman Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  postman-tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Install newman
      run: npm install -g newman newman-reporter-htmlextra

    - name: Verify collection.json exists
      run: ls -la postman\collection.json

    - name: Run Postman Collection
      run: |
        newman run postman\collection.json --reporters=cli,htmlextra --reporter-htmlextra-export newman/report.html

    - name: Report
      uses: actions/upload-artifact@v4
      with:
        name: html_report
        path: ./newman/*.html
